config/routes.rb
FlightBooker::Application.routes.draw do
  root 'flights#index'
  
  get "flights" => 'flights#index'

  resources :bookings, only: [:new, :create, :show]

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :departing_flights, :foreign_key => "from_airport_id", class_name: "Flight"
  has_many :arriving_flights, :foreign_key => "to_airport_id", class_name: "Flight"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  has_many :tickets
  has_many :passengers, :through => :tickets
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base

  belongs_to :from_airport, :class_name => "Airport"
  belongs_to :to_airport, :class_name => "Airport"
  has_many :bookings
  has_many :passengers, :through => :bookings

  def self.search(params)
    if params[:search] && !params[:date].blank?
      date = params[:date].to_date
      Flight.where(from_airport_id: params[:from], to_airport_id: params[:to],
                   date: date.beginning_of_day..date.end_of_day)
            .includes(:from_airport, :to_airport) # prevents N + 1 queries
    else
      Flight.none
    end
  end

  def self.get_dates
    pluck(:date).map{ |d| [ d.strftime("%m/%d/%Y"), d.to_date] }.uniq
  end


  def date_formatted
    date.strftime("%m/%d/%Y")
  end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  has_many :tickets
  has_many :bookings, :through => :tickets
  has_many :flights, :through => :bookings

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :booking
  belongs_to :passenger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.build

    params[:passengers].to_i.times { @booking.passengers.build }
    @booking.passengers.build if params[:passengers].blank? #one passenger by default (user forgot to select)
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      @booking.passengers.each { |p| PassengerMailer.thank_you_email(p).deliver! }
       
      redirect_to booking_path(@booking)
      
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

   private
    def booking_params
      params.require(:booking).permit(:flight_id,
                                      :passengers_attributes => [:name, :email] )
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.search(params)
    @airports = Airport.pluck(:code, :id).sort
    @dates = Flight.get_dates
    @passengers = (1..4).map { |p| [  p.to_s + " passenger".pluralize(p), p] }
  end    
end

app/helpers/application_helper.rb
module ApplicationHelper
  include FoundationRailsHelper::FlashHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper

end

app/views/bookings/new.html.erb
<% provide(:title, 'Booking') %>
<h1>Booking Page</h1>

<fieldset>
  <legend>Trip Details</legend>
  <h3>Flight #<%= @flight.id %></h3>
  <h3>
  <%= @flight.from_airport.code %> -> <%= @flight.to_airport.code %>
  <small><%=@flight.from_airport.city%> to <%=@flight.to_airport.city%></small>
  </h3>
  <p><%= @flight.date.strftime("%A, %B %d, %Y") %></p>
</fieldset>

<div class="row">
  <div class="large-6 columns">
    <%= form_for(@booking) do |f| %>
      <%= f.hidden_field :flight_id %>         
      <fieldset>
        <legend>Passengers Information</legend>
        <%= f.fields_for :passengers do |passenger| %>
        <div class="row">
           <div class="large-6 columns">
            <%= passenger.text_field :name %>
           </div>
           <div class="large-6 columns">
          <%= passenger.text_field :email %>
          </div>    
        </div>    
        <% end %>
      </fieldset>
      <%= f.submit "Book Flight", class: "button" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<% provide(:title, 'Confirmation') %>
<h1>Booking Confirmation</h1>

<p>
  Thank you for booking your flight with flight-booker.  
  Your confirmation # is <b><%= @booking.id %></b>.
</p>

<p>
  Flight #<%= @booking.flight.id %>: <%= @booking.flight.from_airport.code %> -> 
  <%= @booking.flight.to_airport.code %> on 
  <%= @booking.flight.date.strftime("%A, %B %d, %Y") %>.
</p>

<p>Passengers:</p>
<ol>
<% @booking.passengers.each do |passenger| %>
 <li> <%="#{passenger.name} <#{passenger.email}>" %></li>
<% end %>
</ol>

app/views/flights/_search.html.erb
<%= form_tag flights_path, method: 'get' do %>
<div class="row">
  <%= hidden_field_tag :search %>
  <div class="large-2 columns">
    <%= select_tag :from, options_for_select(@airports),  prompt: "From" %>
  </div>

  <div class="large-2 columns">
    <%= select_tag :to, options_for_select(@airports), prompt: "To" %>
  </div>

  <div class="large-2 columns">
      <%= select_tag :date, options_for_select(@dates), prompt: "Date" %>
  </div>

  <div class="large-2 columns">
    <%= select_tag :passengers, options_for_select(@passengers), prompt: "passengers" %>
  </div>
   
  <div class="large-4 columns">
    <%= submit_tag "Search", :name => nil, class: "button" %>
  </div>
</div>
<% end %>

app/views/flights/_search_results.html.erb
<%= form_tag new_booking_path, method: 'get' do %>
  <div class="row">
  <table>
  <thead>
    <tr>
      <th width = "50">Select</th>
      <th width ="110">Flight #</th>
      <th width ="150">Date</th>
      <th width ="150">Departs</th>
      <th width ="110">From</th>
      <th width ="110">To</th>
      <th width ="110">Duration</th>
    </tr>
  </thead>

    <% @flights.each do |flight| %>
      <tbody>
        <tr>
          <td><%= radio_button_tag :flight_id, flight.id %></td>
          <td><%= flight.id %></td>
          <td><%= flight.date.strftime("%B %d, %Y")  %></td>
          <td><%= flight.date.strftime('%I:%M:%S %p') %></td>
          <td><%= flight.from_airport.code %></td>
          <td><%= flight.to_airport.code %></td>
          <td><%= distance_of_time_in_words(flight.duration) %></td>
        </tr>      
      </tbody>
    <% end %>
    </table>
    <%= submit_tag "Select Flight", :name => nil, class: "button" %>
    <%= hidden_field_tag :passengers, params[:passengers] %>

  </div>
<% end %>

app/views/flights/index.html.erb
<% provide(:title, 'Search Flights') %>
<h1>Flights</h1> 

<%= render 'search' %>

<% if !@flights.none? %>
  <%= render 'search_results' %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Copyright no one at all. Go to town.</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
            <%= link_to "Home", root_path %>

        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="row">
  <div class="large-3 columns">
    <h1><%= image_tag "globe-swooshes-logo.jpg" %></h1>
  </div>
  <div class="large-9 columns">
    <ul class="button-group">
        <%= link_to "Home", root_path, class: "button" %>
        <a class="button" href="https://github.com/Jberczel/Flight_Booker">Source Code</a>

    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>    
        <p><%= debug(params) if Rails.env.development? %></p>
      </div>
    </div>   

    <%= javascript_include_tag "application" %>
  </body>
</html>